[package]
name = "spaced-typing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spaced-rs = "0.3"
termion = "1.5"
rand = "0.8"